---
abstract: 'Send mails with attachments through a SMTP server, socket()s based.'
author:
  - 'Jan Krynicky (Jenda@Krynicky.cz)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Sender
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: 0
version: v0.8.23
